protected/modules/staff/controllers/SubscribeController.php
<?php

class SubscribeController extends Controller
{
	public $layout = "/layouts/main";

	public $canWithoutLogin = array();
	function init() {
		$this->canWithoutLogin = array('login');

		if(!isset(Yii::app()->session['stuff'])) {
			if (!in_array($this->action, $this->canWithoutLogin)) {
				$this->redirect($this->CreateUrl('default/login'));
			}
		}
	}

	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Subscribe;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subscribe']))
		{
			$model->attributes=$_POST['Subscribe'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subscribe']))
		{
			$model->attributes=$_POST['Subscribe'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Subscribe');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Subscribe('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Subscribe']))
			$model->attributes=$_GET['Subscribe'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Subscribe the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Subscribe::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Subscribe $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='subscribe-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionSendEmail(){
		if(isset($_POST['send'])) {
			$subject = $_POST['send']['subject'];
			$message = $_POST['send']['message'];
			set_time_limit(0);
			$limit = 50;
			$subscribe = Subscribe::model()->findAll();
			foreach ($subscribe as $key => $value) {

				if ($this->sendEmailForAllUser($value->email, $subject, $message)) {
				} else {
					$dont_send = new DontSendUser();
					$dont_send->user_id = $value->id;
					$dont_send->date = date('Y-m-d H:i:s');
					$dont_send->save();
				}
			}
			$this->redirect($this->CreateUrl('DontSendUser/admin'));

		}
		$this->render('send_email');
	}

	protected function sendEmailForAllUser($email,$subject, $message) {
		$mail = Yii::app()->params->adminEmail;
		$password = Yii::app()->params->password;
		$smtp = Yii::app()->params->smtp;
		$mailSMTP = new SendMailSmtpClass( $mail, $password, 'ssl://'.$smtp, $mail, 465);

		$headers= "MIME-Version: 1.0\r\n";
		$headers .= "Content-type: text/html; charset=utf-8\r\n";
		$headers .= "From:  <$mail>\r\n";
		$result =  $mailSMTP->send("$email",
			"

            : ".$subject,
			$message." <br/> <a href=".$this->createUrl("/site/unsubscribe",array('email'=>$email))." > Unsubscribe </a>",
			$headers);
		if($result === true){
			return true;
		}else {
			return false;
		}
	}
}

protected/modules/staff/views/subscribe/_form.php
<section class="content">
	<div class="row">
		<!-- left column -->
		<div class="col-md-12">
			<!-- general form elements -->
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title"><p class="note">Fields with <span class="required">*</span> are required.</p></h3>
				</div>

					<?php $form=$this->beginWidget('CActiveForm', array(
						'id'=>'subscribe-form',
						'enableAjaxValidation'=>false,
						'htmlOptions' => array(
							'class' =>'form-horizontal',
							"enctype" => "multipart/form-data"
						)
					)); ?>

						<?php echo $form->errorSummary($model); ?>

						<div class="form-group">
							<?php echo $form->labelEx($model,'email',array('class'=>'col-sm-2 control-label')); ?>
							<div class="col-sm-10">
								<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>250, 'class' => 'form-control')); ?>
							</div>
							<?php echo $form->error($model,'email'); ?>
						</div>

						<div class="form-group hide">
							<?php echo $form->labelEx($model,'created_date',array('class'=>'col-sm-2 control-label')); ?>
							<div class="col-sm-10">
								<?php echo $form->textField($model,'created_date', array('class' => 'form-control','value' => Helpers::date())); ?>
							</div>
							<?php echo $form->error($model,'created_date'); ?>
						</div>

						<div class="form-group buttons">
							<div class="col-sm-12">
								<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array('class'=>'btn btn-primary pull-right')); ?>
							</div>
						</div>

					<?php $this->endWidget(); ?>

			</div>
		</div>
	</div>
</section>

protected/modules/staff/views/subscribe/_search.php
<?php
/* @var $this SubscribeController */
/* @var $model Subscribe */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created_date'); ?>
		<?php echo $form->textField($model,'created_date'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/staff/views/subscribe/_view.php
<?php
/* @var $this SubscribeController */
/* @var $data Subscribe */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_date')); ?>:</b>
	<?php echo CHtml::encode($data->created_date); ?>
	<br />


</div>

protected/modules/staff/views/subscribe/admin.php
<section class="content-header">
	<h1>
		Subscribe People
	</h1>

</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Subscribe People</h3>
					<a href="<?=$this->CreateUrl('subscribe/create')?>" class="btn btn-primary pull-right">Add New</a>
				</div>
				<!-- /.box-header -->
				<div class="box-body">

						<?php $this->widget('zii.widgets.grid.CGridView', array(
							'id'=>'subscribe-grid',
							'dataProvider'=>$model->search(),
							'filter'=>$model,
							'columns'=>array(
								'id',
								'email',
								'created_date',
								array(
									'class' => 'zii.widgets.grid.CButtonColumn',
									'htmlOptions' => array('style' => 'white-space: nowrap'),
									'afterDelete' => 'function(link,success,data) { if (success && data) alert(data); }',
									'buttons' => array(
										'view' => array(
											'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'View'),'class'=>'img-btn hide'),
											'label' => '<i class="fa fa-eye"></i>',
											'imageUrl' => false,
										),
										'update' => array(
											'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'Update'),'class'=>'img-btn'),
											'label' => '<i class="fa fa-pencil"></i>',
											'imageUrl' => false,
										),
										'delete' => array(
											'options' => array('rel' => 'tooltip', 'data-toggle' => 'tooltip', 'title' => Yii::t('app', 'Delete'),'class'=>'img-btn del-btn'),
											'label' => '<i class="fa fa-times"></i>',
											'imageUrl' => false,
										)
									)
								),
							),
						)); ?>
				</div>
			</div>
		</div>
	</div>
</section>

protected/modules/staff/views/subscribe/create.php
<?php
/* @var $this SubscribeController */
/* @var $model Subscribe */

$this->breadcrumbs=array(
	'Subscribes'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Subscribe', 'url'=>array('index')),
	array('label'=>'Manage Subscribe', 'url'=>array('admin')),
);
?>

<h1>Create Subscribe</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/staff/views/subscribe/index.php
<?php
/* @var $this SubscribeController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Subscribes',
);

$this->menu=array(
	array('label'=>'Create Subscribe', 'url'=>array('create')),
	array('label'=>'Manage Subscribe', 'url'=>array('admin')),
);
?>

<h1>Subscribes</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/modules/staff/views/subscribe/send_email.php
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"><p class="note">Fields with <span class="required">*</span> are required.</p></h3>
                </div>
                        <form class="form-horizontal" action="<?=$this->CreateUrl('subscribe/SendEmail')?>" method="post">
                            <div class="form-group">
                                <div class="col-sm-2 control-label">
                                    Subject
                                </div>
                                <div class="col-sm-10">
                                    <input type="text" name="send[subject]" class="form-control" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-2 control-label">
                                    Message
                                </div>
                                <div class="col-sm-10">
                                    <textarea class="form-control" id="editor" name="send[message]" required></textarea>
                                </div>
                            </div>
                            <div class="form-group buttons">
                                <div class="col-sm-12">
                                    <button class="btn btn-primary pull-right">Send</button>
                                </div>
                            </div>
                        </form>

            </div>
        </div>
    </div>
</section>
<script>
    $(function () {
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.

        CKEDITOR.replace( 'editor', {});
        //bootstrap WYSIHTML5 - text editor
        $(".textarea").wysihtml5();



    });
</script>

protected/modules/staff/views/subscribe/update.php
<?php
/* @var $this SubscribeController */
/* @var $model Subscribe */

$this->breadcrumbs=array(
	'Subscribes'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Subscribe', 'url'=>array('index')),
	array('label'=>'Create Subscribe', 'url'=>array('create')),
	array('label'=>'View Subscribe', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Subscribe', 'url'=>array('admin')),
);
?>

<h1>Update Subscribe <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/staff/views/subscribe/view.php
<?php
/* @var $this SubscribeController */
/* @var $model Subscribe */

$this->breadcrumbs=array(
	'Subscribes'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Subscribe', 'url'=>array('index')),
	array('label'=>'Create Subscribe', 'url'=>array('create')),
	array('label'=>'Update Subscribe', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Subscribe', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Subscribe', 'url'=>array('admin')),
);
?>

<h1>View Subscribe #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'email',
		'created_date',
	),
)); ?>